### ISSUE TITLE
shader compile error on mesa

### ISSUE THREAD

**Issue by jeffallen** [g3n/g3nd#2]
On Ubuntu 16.04.2 with:
 08:04:38.087191:I:G3ND:OpenGL version: 3.3 (Core Profile) Mesa 12.0.6
08:04:38.096676:I:G3ND:OpenAL Community version: 1.1 ALSOFT 1.16.0
08:04:38.097110:I:G3ND:Xiph.Org libVorbis 1.3.5

I get only a grey screen. With "-logs gui:debug" I get:

07:58:58.852209:W:G3N/GUI:Invalid panel width:-202
07:58:58.852699:W:G3N/GUI:Invalid panel width:-306
07:58:58.856393:W:G3N/GUI:Invalid panel width:-306
07:58:58.856438:W:G3N/GUI:Invalid panel height:-48
07:58:58.856451:W:G3N/GUI:Invalid panel width:-306
07:58:58.856471:W:G3N/GUI:Invalid panel height:-48
07:58:58.856478:W:G3N/GUI:Invalid panel width:-202
07:58:58.856484:W:G3N/GUI:Invalid panel height:-48

If I add a panic where the width is checked, I see this call stack:

github.com/g3n/engine/gui.(*Panel).SetSize(0xc42002fc00, 0xc34a0000)
	/home/jra/src/github.com/g3n/engine/gui/panel.go:247 +0x1ce
github.com/g3n/engine/gui.(*Panel).SetWidth(0xc42002fc00, 0xc34a0000)
	/home/jra/src/github.com/g3n/engine/gui/panel.go:261 +0x45
github.com/g3n/engine/gui.(*HBoxLayout).Recalc(0xc42054c200, 0xc61f80, 0xc420568000)
	/home/jra/src/github.com/g3n/engine/gui/hboxlayout.go:127 +0x9d1

Adding this debug line before hboxlayout.go:127 gives "iwidth = (0 - 0 - 202 - 0) * 1 / 1"

	log.Debug("iwidth = (%v - %v - %v - %v) * %v / %v", parent.ContentWidth(), spacing, fwidth, bl.spacing, params.Expand, texpand)

So parent.ContentWidth() is zero when you expect it to have already been set.

However, when I drag the corner to resize, I start getting lines like these, but the windows stays all grey.

08:20:55.529015:D:G3N/GUI:iwidth = (869 - 0 - 323 - 0) * 1 / 1
08:20:55.557535:D:G3N/GUI:iwidth = (872 - 0 - 323 - 0) * 1 / 1
08:20:55.582883:D:G3N/GUI:iwidth = (875 - 0 - 323 - 0) * 1 / 1
08:20:55.623262:D:G3N/GUI:iwidth = (879 - 0 - 323 - 0) * 1 / 1

I need to stop debugging there, good luck!

**Comment by leonsal** [comment]
I don't think that the invalid panel width/height warnings are the cause of the problem.
These warnings occur even when the rendering is OK.

Do you a have a GPU and its driver installed in your system ?
Your first log line indicates the Mesa OpenGL implementation which is a software only implementation.
`08:04:38.087191:I:G3ND:OpenGL version: 3.3 (Core Profile) Mesa 12.0.6`

In my system, for example, this log line is:
`11:28:27.461786:I:G3ND:OpenGL version: 3.3.0 NVIDIA 367.57`

You can eliminate the GUI warning by running a demo without any GUI:
`>g3nd -nogui geometry.box`

Does it show an image ?

**Comment by jeffallen** [comment]
Failing to compile vertex shader?

```
$ ./g3nd -nogui geometry.box
15:08:52.392522:I:G3ND:G3N Demo v0.1 starting
15:08:52.392558:I:G3ND:Using data directory:data
15:08:52.445447:I:G3ND:OpenGL version: 3.3 (Core Profile) Mesa 12.0.6
15:08:52.455738:I:G3ND:OpenAL Community version: 1.1 ALSOFT 1.16.0
15:08:52.455969:I:G3ND:Xiph.Org libVorbis 1.3.5
15:08:52.465771:F:G3ND:Render error: Error compiling Vertex Shader: 0:6(1): error: storage qualifiers must come after precise, invariant, interpolation, layout and auxiliary storage qualifiers
0:7(1): error: storage qualifiers must come after precise, invariant, interpolation, layout and auxiliary storage qualifiers
0:8(1): error: storage qualifiers must come after precise, invariant, interpolation, layout and auxiliary storage qualifiers
0:9(1): error: storage qualifiers must come after precise, invariant, interpolation, layout and auxiliary storage qualifiers
0:10(1): error: storage qualifiers must come after precise, invariant, interpolation, layout and auxiliary storage qualifiers
0:11(1): error: storage qualifiers must come after precise, invariant, interpolation, layout and auxiliary storage qualifiers
001:
002:#version 330 core
003:
004:
005:// Vertex attributes
006:in layout(location = 0) vec3  VertexPosition;
007:in layout(location = 1) vec3  VertexNormal;
008:in layout(location = 2) vec3  VertexColor;
009:in layout(location = 3) vec2  VertexTexcoord;
010:in layout(location = 4) float VertexDistance;
011:in layout(location = 5) vec4  VertexTexoffsets;
012:
013:
014:// Model uniforms
015:uniform mat4 ModelViewMatrix;
016:uniform mat3 NormalMatrix;
017:uniform mat4 MVP;
018:
019:
020:
021:// Ambient lights uniforms
022:uniform vec3 AmbientLightColor[1];
023:
024:
025:
026:// Directional lights uniforms
027:uniform vec3  DirLightColor[1];
028:uniform vec3  DirLightPosition[1];
029:
030:
031:
032:
033:
034:
035:
036:// Material uniforms
037:uniform vec3      MatAmbientColor;
038:uniform vec3      MatDiffuseColor;
039:uniform vec3      MatSpecularColor;
040:uniform float     MatShininess;
041:uniform vec3      MatEmissiveColor;
042:uniform float     MatOpacity;
043:
044:
045:
046:
047:/***
048: phong lighting model
049: Parameters:
050:    position:   input vertex position in camera coordinates
051:    normal:     input vertex normal in camera coordinates
052:    camDir:     input camera directions
053:    matAmbient: input material ambient color
054:    matDiffuse: input material diffuse color
055:    ambdiff:    output ambient+diffuse color
056:    spec:       output specular color
057: Uniforms:
058:    AmbientLightColor[]
059:    DiffuseLightColor[]
060:    DiffuseLightPosition[]
061:    PointLightColor[]
062:    PointLightPosition[];
063:    PointLightLinearDecay[];
064:    PointLightQuadraticDecay[];
065:    MatSpecularColor
066:    MatShininess
067:*/
068:void phongModel(vec4 position, vec3 normal, vec3 camDir, vec3 matAmbient, vec3 matDiffuse, out vec3 ambdiff, out vec3 spec) {
069:
070:    vec3 ambientTotal  = vec3(0.0);
071:    vec3 diffuseTotal  = vec3(0.0);
072:    vec3 specularTotal = vec3(0.0);
073:
074:    
075:    for (int i = 0; i < 1; i++) {
076:        ambientTotal += AmbientLightColor[i] * matAmbient;
077:    }
078:    
079:
080:    
081:    for (int i = 0; i < 1; i++) {
082:        // Diffuse reflection
083:        // DirLightPosition is the direction of the current light
084:        vec3 lightDirection = normalize(DirLightPosition[i]);
085:        // Calculates the dot product between the light direction and this vertex normal.
086:        float dotNormal = max(dot(lightDirection, normal), 0.0);
087:        diffuseTotal += DirLightColor[i] * matDiffuse * dotNormal;
088:
089:        // Specular reflection
090:        // Calculates the light reflection vector 
091:        vec3 ref = reflect(-lightDirection, normal);
092:        if (dotNormal > 0.0) {
093:            specularTotal += DirLightColor[i] * MatSpecularColor * pow(max(dot(ref, camDir), 0.0), MatShininess);
094:        }
095:    }
096:    
097:
098:    
099:
100:    
101:
102:    // Sets output colors
103:    ambdiff = ambientTotal + MatEmissiveColor + diffuseTotal;
104:    spec = specularTotal;
105:}
106:
107:
108:
109:// Outputs for the fragment shader.
110:out vec3 ColorFrontAmbdiff;
111:out vec3 ColorFrontSpec;
112:out vec3 ColorBackAmbdiff;
113:out vec3 ColorBackSpec;
114:out vec2 FragTexcoord;
115:
116:void main() {
117:
118:    // Transform this vertex normal to camera coordinates.
119:    vec3 normal = normalize(NormalMatrix * VertexNormal);
120:
121:    // Calculate this vertex position in camera coordinates
122:    vec4 position = ModelViewMatrix * vec4(VertexPosition, 1.0);
123:
124:    // Calculate the direction vector from the vertex to the camera
125:    // The camera is at 0,0,0
126:    vec3 camDir = normalize(-position.xyz);
127:
128:    // Calculates the vertex Ambient+Diffuse and Specular colors using the Phong model
129:    // for the front and back
130:    phongModel(position,  normal, camDir, MatAmbientColor, MatDiffuseColor, ColorFrontAmbdiff, ColorFrontSpec);
131:    phongModel(position, -normal, camDir, MatAmbientColor, MatDiffuseColor, ColorBackAmbdiff, ColorBackSpec);
132:
133:    vec2 texcoord = VertexTexcoord;
134:    
135:    FragTexcoord = texcoord;
136:
137:    gl_Position = MVP * vec4(VertexPosition, 1.0);
138:}
139:


panic: LOG FATAL

goroutine 1 [running, locked to thread]:
github.com/g3n/engine/util/logger.(*Logger).Log(0xc4201c6fc0, 0x4, 0x829e4f, 0x11, 0xc4200a7d98, 0x1, 0x1)
	/home/jra/src/github.com/g3n/engine/util/logger/logger.go:253 +0x894
github.com/g3n/engine/util/logger.(*Logger).Fatal(0xc4201c6fc0, 0x829e4f, 0x11, 0xc4200a7d98, 0x1, 0x1)
	/home/jra/src/github.com/g3n/engine/util/logger/logger.go:194 +0x66
main.main()
	/home/jra/src/github.com/g3n/g3nd/main.go:241 +0x1032

```

My graphics card is an i915, glxgears works, and shows:

$ glxgears -info
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
GL_RENDERER   = Mesa DRI Intel(R) Ivybridge Desktop 
GL_VERSION    = 3.0 Mesa 12.0.6
GL_VENDOR     = Intel Open Source Technology Center

**Comment by jeffallen** [comment]
Found a potential fix, sending PR in a bit.
